### ISSUE TITLE
Wrong schema in schema link

### ISSUE THREAD

**Issue by maksle** [FDA/openfda#137]
[https://download.open.fda.gov/2020-07-11/device/enforcement/recall_schema.json
](https://download.open.fda.gov/2020-07-11/device/enforcement/recall_schema.json
)
This link is from https://download.open.fda.gov/

It appears to have the drug enforcement schema properties in openfda when you visit the page. Is it correct?

**Comment by maksle** [comment]
It is also missing `postal_code`

**Comment by maksle** [comment]
`openfda` field is always empty for device enforcement, which I don't know whether it is due to this schema problem

**Comment by dkrylovsb** [comment]
The thing is, the three Enforcement endpoints -- Drug/Device/Food Recall Enforcement Reports -- are served from a single Elasticsearch index internally. `product_type` is used as a differentiator for the nouns as can be seen for example [here](https://github.com/FDA/openfda/blob/master/api/faers/api.js#L852). A side effect of that is that the harmonization section (`openfda`) is only provided for one of the nouns, i.e. _Drugs_. It remains empty for Devices and Food by design.

We'll add postal code shortly. Thanks for catching this.

**Comment by dkrylovsb** [comment]
`postal_code` added.
