### ISSUE TITLE
Origin of the "drugcharacterization" field in the drug adverse events API

### ISSUE THREAD

**Issue by eric-czech** [FDA/openfda#195]
Is it possible to get some information on where the `drugcharacterization` field comes from in the adverse events API?  I understand (based on this [notebook](https://github.com/neksa/openfda-faers/blob/master/OpenFDA%20API%20for%20FAERS.ipynb)) that it is intended to indicate whether or not the drug for a record is presumed to be causal for a reaction, and that this is true for most reports.  Where does this come from though?  Is that information provided by the reporters of the event?  Is any part of this determination automated?  

Thanks!

**Comment by dkrylovsb** [comment]
`drugcharacterization` indicates reported role of drug in adverse event. Possible Codes are: 1= suspect  2=concomitant 3= interacting. openFDA receives this information from the FDA Adverse Event Reporting System (FAERS) Quarterly Data Extract Files.

For any given report, there is no certainty that a suspected drug caused the reaction. This is because physicians are encouraged to report suspected reactions; however, the event may have been related to the underlying disease being treated, or caused by some other drug being taken concurrently, or simply occurred by chance at that time.

Hope this helps.

**Comment by eric-czech** [comment]
It does, thank you @dkrylovsb 👍
