### ISSUE TITLE
ElasticSearch 'multi_field' type deprecated

### ISSUE THREAD

**Issue by westurner** [FDA/openfda#44]
- http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/_multi_fields.html

> the field type multi_field has been removed.

Affected schema:
- https://github.com/FDA/openfda/blob/master/schemas/faers_mapping.json
- https://github.com/FDA/openfda/blob/master/schemas/maude_mapping.json
- https://github.com/FDA/openfda/blob/master/schemas/res_mapping.json

**Comment by HansNelsen** [comment]
Thanks for catching this! 

The good news is that ES will auto convert to the new syntax when you pass in the deprecated mapping (which is why you get a different response from localhost:9200/<index>/_mappings. 

I will mark this as bug since it is unclear how long ES will convert the old syntax automatically.

**Comment by westurner** [comment]
Thanks!

* http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/_deprecations.html
* https://docs.python.org/2/library/exceptions.html#exceptions.PendingDeprecationWarning would be great
