### ISSUE TITLE
API Status Page Not Updating 

### ISSUE THREAD

**Issue by GeekNurse** [FDA/openfda#46]
Several are not updating appropriately with dates back to 11/2014 
![screen shot 2015-01-31 at 2 11 35 pm](https://cloud.githubusercontent.com/assets/2581355/5989359/29ed31ca-a953-11e4-976e-7dcd1795653b.png)
![screen shot 2015-01-31 at 2 11 24 pm](https://cloud.githubusercontent.com/assets/2581355/5989360/29ed4b7e-a953-11e4-8816-7ee016871ccc.png)
![screen shot 2015-01-31 at 1 43 06 pm](https://cloud.githubusercontent.com/assets/2581355/5989358/29ec7fd2-a953-11e4-9210-75afaf0cb96d.png)

**Comment by HansNelsen** [comment]
We are currently in the process of migrating each index to be incrementally updated. The deviceevent index is the last in the migration queue. It should be updated relatively quickly. I do not have an exact ETA for the push, but it should be relatively quickly.

Once the change is in place, the updates for the deviceevent will be inline with the volatility of the data, which is to say, since it is updated once a month, the index will be refreshed once a month.

**Comment by HansNelsen** [comment]
The migration to the incremental updates is complete and the /device/event.json endpoint is being updated monthly, per its sources update cycle.

I will close this issue.

Thank you for using the openFDA.
