### ISSUE TITLE
issue with getting data for state of Oregon

### ISSUE THREAD

**Issue by harjitdotsingh** [FDA/openfda#60]
when I pass is this request

http://api.fda.gov/food/enforcement.json?search=soy+AND+status:OnGoing+AND+state:OR&limit=100

I get an BAD REQUEST back as the result. 

When I change the state to any other state , it works fine

**Comment by mattmo** [comment]
You can either enclose the state in quotes or use a lowercase version of the state, since the match is not case sensitive:

Quotes:

http://api.fda.gov/food/enforcement.json?search=soy+AND+status:OnGoing+AND+state:"OR"&limit=100

Lowercase:

http://api.fda.gov/food/enforcement.json?search=soy+AND+status:OnGoing+AND+state:or&limit=100
