### ISSUE TITLE
The schema schemas/downloads_mapping.json is malformed

### ISSUE THREAD

**Issue by michael-newsrx** [FDA/openfda#83]
When processing the schema for downloads, I was unable to generate a Java POJO.

After comparison with the other schemas it appears to be malformed.

It starts with:

```
{
  "downloads": {
    "dynamic": "strict",
"properties": {
```

instead of something like:
```
{
  "$schema": "http://json-schema.org/draft-03/schema",
    "properties": {
      "device": {
```

**Comment by gundalar** [comment]
@michael-newsrx, we verified that the JSON file, schemas/downloads_mapping.json is a valid one. We are able to successfully deserialize and convert it into POJOs using JSON to POJO converter tools. Didn't face any issues.

The property, "$schema": "http://json-schema.org/draft-03/schema" is used to specify the version of JSON schema, the absence of which the tool or whatever application will use the latest JSON schema version available to it. It is not mandatory per my understanding.

Can you please let us know the program/tool that you are using to convert the JSON to POJOs so that we can try to reproduce that error on our end? Also please try other mapping files, which do not specify $schema property, for instance schemas/foodevent_mapping.json and let us know if you run into same issues.

**Comment by michael-newsrx** [comment]
The tool we are using is: http://www.jsonschema2pojo.org/ (I should have provided this before, sorry!)

When provided the existing schema file it results in no output.

**Comment by gundalar** [comment]
I am able to generate the output for downloads_mapping.json (without any modifications to it) using [embedding in Java code using jsonschema2pojo-core](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Getting-Started#using-jsonschema2pojo-within-your-java-project-embedded). I had to tweak the code a bit as it wasn't working for all mapping files as is.

I couldn't get it to work using the CLI or maven approach they listed.
