### ISSUE TITLE
Duplicate results Within Enforcement

### ISSUE THREAD

**Issue by CalebYates1** [FDA/openfda#94]
Was doing a call and noticed that 3 out of the 4 results I got were duplicated. Is this by design or a bug or some other aspect?

API search
https://api.fda.gov/device/enforcement.json?search=status:Ongoing+AND+(product_description:PM1240+OR+PM1260+OR+PM1272)&limit=100

**Comment by CalebYates1** [comment]
Similar issue within recall
https://api.fda.gov/device/recall.json?search=product_res_number.exact:Z-0030-2018&limit=100

**Comment by dkrylovsb** [comment]
Thanks for reporting! Enforcement: appears to be a bug indeed; we'll work on fixing it. Device Recall: `Z-0030-2018` appears 3 times in the _source_ CSV data provided to us by the agency. We'll try to find out the reason, and if it turns out to be dupes in the source data, we'll adjust the pipeline to filter them out. Thanks again.

**Comment by CalebYates1** [comment]
I did notice that some of the duplicates in thee enforcement do have a slight difference in the code_info so wasnt sure if the duplicate was due to a bucket overflow

**Comment by dkrylovsb** [comment]
Yes, as of today the code uses too many fields to generate a hash and produce an unique ID for a report as can be seen [here](https://github.com/FDA/openfda/blob/master/openfda/res/pipeline.py#L150). So even a small variation can change the ID value and produce a duplicate.

**Comment by dkrylovsb** [comment]
The fix is now in Production.
